language: node_js

jobs:
  include:
    - os: linux
      node_js: "10"
    - os: linux
      node_js: "12"
    - os: linux
      node_js: "13"
    - os: linux
      node_js: "stable"
    - os: windows
      node_js: "14"

cache:
  yarn: true
  directories:
    - node_modules

script: "cross-env-shell yarn run travis"

after_success:
  - cross-env-shell yarn run test:coveralls
  - rimraf ./coverage
